name: cephalometry
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - lightning
  - pandas
  - torchvision
  - pillow
  - tqdm
  - tensorboard
  - matplotlib
  - timm
  - transformers
