#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Chen-ConvNext
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=16:00:00
#SBATCH --output=job_logs/Chen-ConvNext.out

module purge
module load 2022
module load Anaconda3/2022.05

export CUBLAS_WORKSPACE_CONFIG=:4096:8

cd $HOME/Cephalometry
conda activate cephalometry
pip install -r requirements.txt
python experiment --model_name ChenConvNext --batch_size 1 --num_runs 3
