#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ALD
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=16:00:00
#SBATCH --output=job_logs/ALD_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

export CUBLAS_WORKSPACE_CONFIG=:4096:8

cd $HOME/Cephalometry/baselines/Anatomic/Landmark-Detection
conda activate cephalometry
python main.py --new_dataset --landmarkNum 44
