#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ConvNext_adam_tiny
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=16:00:00
#SBATCH --output=job_logs/ConvNext_adam_tiny_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/Cephalometry
conda activate cephalometry
pip install -r requirements.txt
python experiment --model_name ConvNextV2 --optimizer adam --num_runs 3 --model_size tiny
