#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Kim
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=16:00:00
#SBATCH --output=job_logs/Kim_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

export CUBLAS_WORKSPACE_CONFIG=:4096:8

cd $HOME/Cephalometry
conda activate cephalometry
pip install -r requirements.txt
python experiment --model_name Kim --num_runs 3
