#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Yao
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=38:00:00
#SBATCH --output=job_logs/Yao_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

export CUBLAS_WORKSPACE_CONFIG=:4096:8

cd $HOME/Cephalometry
conda activate cephalometry
pip install -r requirements.txt
python experiment --model_name Yao --num_runs 3 --max_hours_per_run 12
